name: CICD Process

on:
  push:
    branches:
      - test-actions

env:
  IMAGE_NAME: flaskapp
  NAMESPACE: project

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }},
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Update deployment file
      run: |
        sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:.*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" kubernetes/flaskapp/deployment.yml
        git add kubernetes/flaskapp/deployment.yml
        git commit -m "Update image version in deployment file"
        git push

    - name: Apply new deployment
      uses: appleboy/kubectl-action@master
      with:
        args: apply -n ${{ env.NAMESPACE }} -f kubernetes/flaskapp/deployment.yml